@startuml API Framework
title Framework Class Diagram

<style>
classDiagram {
  BackgroundColor Snow
  FontColor DarkMagenta
  FontName arial
  FontSize 20
  LineColor DarkViolet
  
  class {
    BackgroundColor LightCyan
  }
}
</style>
skinparam roundCorner 15
skinparam Shadowing false
skinparam ClassBorderThickness 1
skinparam CircledCharacterFontColor DarkViolet
'skinparam CircledCharacterFontSize 15'
'skinparam CircledCharacterRadius 10'

'note right of GameManager
note as A

  하얀 다이아 연결 : Aggregation, 객체와 별개

  까만 다이아 연결 : Composition, 같이 없어짐

end note

class GameManager <<(C, Aqua)>>
class Timer <<(C, Aqua)>>

class Input <<(C, Aqua)>>
class PathManager <<(C, Aqua)>>
class PathInfo <<(S, DeepSkyBlue)>>

class CollisionManager <<(C, Aqua)>>
class CollisionProfile <<(S, DeepSkyBlue)>>

class SceneManager <<(C, Aqua)>>
class Scene <<(C, Aqua)>>
class GameObject <<(C, Aqua)>>
class Camera <<(C, Aqua)>>
class SceneCollision <<(C, Aqua)>>
class SceneResource <<(C, Aqua)>>
class WidgetWindow <<(C, Aqua)>>
class Widget <<(C, Aqua)>>

class ResourceManager <<(C, Aqua)>>
class TextureManager <<(C, Aqua)>>
class Texture <<(C, Aqua)>>
class ImageInfo <<(S, DeepSkyBlue)>>

class AnimationManager <<(C, Aqua)>>
class AnimationSequence <<(C, Aqua)>>
class Animation <<(C, Aqua)>>
class AnimationInfo <<(C, Aqua)>>
class AnimationNotify <<(S, DeepSkyBlue)>>
class AnimationFrameData <<(S, DeepSkyBlue)>>

class SoundManager <<(C, Aqua)>>
class Sound <<(C, Aqua)>>

class FontManager <<(C, Aqua)>>
class Font <<(C, Aqua)>>

abstract class Collider
class ColliderBox <<(C, Aqua)>>
class ColliderCircle <<(C, Aqua)>>
class ColliderLine <<(C, Aqua)>>


class CRef <<(C, Aqua)>>
class CGameObject <<(C, Aqua)>>
class CCollider <<(C, Aqua)>>
class CTexture <<(C, Aqua)>>
class CAniamtionSequence <<(C, Aqua)>>
class CSound <<(C, Aqua)>>
class CFont <<(C, Aqua)>>
class CWidget <<(C, Aqua)>>
class CWidgetWindow <<(C, Aqua)>>



GameManager -left- hidden1
hidden1 -up- CRef
CRef <|-left-  CGameObject
CRef <|--  CCollider
CRef <|--  CTexture
CRef <|-right-  CAniamtionSequence
CRef <|--  CSound
CRef <|--  CFont
CRef <|-up-  CWidgetWindow
CRef <|-up-  CWidget


GameManager *-right-> Timer
GameManager -- Input
GameManager -- PathManager
PathManager *--> PathInfo : map >

GameManager -- ResourceManager
ResourceManager *--> TextureManager
ResourceManager *--> AnimationManager
ResourceManager *--> SoundManager
ResourceManager *--> FontManager
TextureManager *----> Texture : map >
AnimationManager *----> AnimationSequence : map >
SoundManager *--> Sound : map >
FontManager *--> Font : map >

TextureManager -- hidden
AnimationManager -- hidden
SoundManager -- hidden
FontManager -- hidden
hidden -- Scene

GameManager -- CollisionManager
CollisionManager *--> CollisionProfile : map >


GameManager -- SceneManager
SceneManager *----> " 1 " Scene
Scene *-left-> " 1 " Camera
Scene *---> " 1 " SceneResource
Scene *---> " 1 " SceneCollision
Scene *--->  GameObject : list >
Scene *--->  WidgetWindow : vector >
WidgetWindow *-->  Widget : vector >
SceneCollision o-->  Collider : vector >
SceneCollision o-->  WidgetWindow : vector >

SceneResource o---> Texture : map >
Texture *--> ImageInfo : vector >
SceneResource o---> AnimationSequence : map >
SceneResource o---> Sound : map >
SceneResource -up---> TextureManager : Find
SceneResource -up---> AnimationManager : Find
SceneResource -up---> SoundManager : Find
SceneResource -up---> FontManager : Find


GameObject *-->  Collider : list >
Collider <|..  ColliderBox
Collider <|..  ColliderCircle
Collider <|..  ColliderLine
SceneCollision -up-> CollisionManager : Check

GameObject o--> Texture
GameObject *--> Animation
Animation *--> AnimationInfo : map >
AnimationInfo *--> AnimationNotify : vector >
AnimationInfo o--> AnimationSequence
AnimationSequence o-> Texture
AnimationSequence *--> AnimationFrameData : vector >

hide hidden
hide hidden1

'stop'
@enduml