@startuml API Framework
title Framework Class Diagram

<style>
classDiagram {
  BackgroundColor Snow
  FontColor DarkMagenta
  FontName arial
  FontSize 20
  LineColor DarkViolet
  
  class {
    BackgroundColor LightCyan
  }
}
</style>
skinparam roundCorner 15
skinparam Shadowing false
skinparam ClassBorderThickness 1
skinparam CircledCharacterFontColor DarkViolet
'skinparam CircledCharacterFontSize 15'
'skinparam CircledCharacterRadius 10'


package Component <<Rectangle>> {
  class SceneComp <<(C, Aqua)>>
  class Primitive <<(C, Aqua)>>
  class StaticMesh <<(C, Aqua)>>
  class AnimationMesh <<(C, Aqua)>>
  class Collider <<(C, Aqua)>>
  class Camera <<(C, Aqua)>>
  class ObjectComp <<(C, Aqua)>>
  class Input <<(C, Aqua)>>
  class RigidBody <<(C, Aqua)>>
}

package Objects <<Rectangle>> {
  class GameObject <<(C, Aqua)>>
  class Player <<(C, Aqua)>>
  class Enemy <<(C, Aqua)>>
  class Weapon <<(C, Aqua)>>
  class BossModule <<(C, Aqua)>>
}

GameObject *-> Component : list >

GameObject <|-- Player
GameObject <|-- Enemy
GameObject <|-- Weapon
GameObject <|-- BossModule

SceneComp <|-- Primitive
Primitive <|-- StaticMesh
Primitive <|-- AnimationMesh
SceneComp <|-- Collider
SceneComp <|-- Camera
ObjectComp <|-- RigidBody
ObjectComp <|-- Input

'stop'
@enduml