@startuml API Framework
title Framework Class Diagram

<style>
classDiagram {
  BackgroundColor Snow
  FontColor DarkMagenta
  FontName arial
  FontSize 20
  LineColor DarkViolet
  
  class {
    BackgroundColor LightCyan
  }
}
</style>
skinparam roundCorner 15
skinparam Shadowing false
skinparam ClassBorderThickness 1
skinparam CircledCharacterFontColor DarkViolet
'skinparam CircledCharacterFontSize 15'
'skinparam CircledCharacterRadius 10'


class SceneManager <<(C, Aqua)>>
class Scene <<(C, Aqua)>>
class MainScene <<(C, Aqua)>>
class StageTutorial <<(C, Aqua)>>
class StageHunt <<(C, Aqua)>>
class StageHole <<(C, Aqua)>>
class StageFrame <<(C, Aqua)>>
class StageCloud <<(C, Aqua)>>
class StageStatic <<(C, Aqua)>>
class StageBoss <<(C, Aqua)>>

class hided
SceneManager *-right--> Scene
Scene -up-- hided
Scene <|- MainScene
hided -left- MainScene
Scene <|- StageTutorial
hided -left- StageTutorial
MainScene -[hidden]- StageTutorial
Scene <|- StageHunt
hided -left- StageHunt
StageTutorial -[hidden]- StageHunt
Scene <|- StageHole
hided -left- StageHole
StageHunt -[hidden]- StageHole
Scene <|- StageFrame
hided -left- StageFrame
StageHole -[hidden]- StageFrame
Scene <|- StageCloud
hided -left- StageCloud
StageFrame -[hidden]- StageCloud
Scene <|- StageStatic
hided -left- StageStatic
StageCloud -[hidden]- StageStatic
Scene <|- StageBoss
'hided -left- StageBoss'
StageStatic -[hidden]- StageBoss

'stop'
@enduml